import { Geist, Geist_Mono } from "next/font/google";
import "../../../../globals.css";
import Navbar from "../../../../components/Navbar"
import SurahNav from "../../../../components/SurahNav"

import { Lato } from 'next/font/google';




const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],     // Include both weights
  style: ['normal', 'italic'], // Include both styles
  variable: '--font-lato',
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${lato.variable}  antialiased overflow-x-hidden over`} 
        
      >
        <Navbar/>
        {/* <SurahNav/> */}
        {children}
      </body>
      
    </html>
  );
}
