
import "../../../../globals.css";


import { Lato } from 'next/font/google';
import { Merriweather } from 'next/font/google';


const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ['400', '700'],     // Include both weights
  style: ['normal', 'italic'], // Include both styles
  variable: '--font-merriweather',
});
const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],     // Include both weights
  style: ['normal', 'italic'], // Include both styles
  variable: '--font-lato',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${lato.variable} ${merriweather.variable} antialiased overflow-x-hidden over`}
      >
        {/* <Navbar/> */}
        {/* <SurahNav/> */}
        {children}
      </body>
      
    </html>
  );
}
