export const surahs = [
  { number: 1, englishName: "The Opening", arabicRoman: "Al-Fatihah", verses: 7 },
  { number: 2, englishName: "The Cow", arabicRoman: "Al-Baqarah", verses: 286 },
  { number: 3, englishName: "The Family of Imran", arabicRoman: "Al ‘Imran", verses: 200 },
  { number: 4, englishName: "The Women", arabicRoman: "Al-Nisa’", verses: 176 },
  { number: 5, englishName: "The Table Spread", arabicRoman: "Al-Ma’idah", verses: 120 },
  { number: 6, englishName: "The Cattle", arabicRoman: "Al-An‘am", verses: 165 },
  { number: 7, englishName: "The Heights", arabicRoman: "Al-A‘raf", verses: 206 },
  { number: 8, englishName: "The Spoils of War", arabicRoman: "Al-Anfal", verses: 75 },
  { number: 9, englishName: "The Repentance", arabicRoman: "Al-Tawbah", verses: 129 },
  { number: 10, englishName: "Jonah", arabicRoman: "Yunus", verses: 109 },
  { number: 11, englishName: "Hud", arabicRoman: "Hud", verses: 123 },
  { number: 12, englishName: "Joseph", arabicRoman: "Yusuf", verses: 111 },
  { number: 13, englishName: "The Thunder", arabicRoman: "Al-Ra‘d", verses: 43 },
  { number: 14, englishName: "Abraham", arabicRoman: "Ibrahim", verses: 52 },
  { number: 15, englishName: "The Rocky Tract", arabicRoman: "Al-Hijr", verses: 99 },
  { number: 16, englishName: "The Bee", arabicRoman: "Al-Nahl", verses: 128 },
  { number: 17, englishName: "The Night Journey", arabicRoman: "Al-Isra’", verses: 111 },
  { number: 18, englishName: "The Cave", arabicRoman: "Al-Kahf", verses: 110 },
  { number: 19, englishName: "Mary", arabicRoman: "Maryam", verses: 98 },
  { number: 20, englishName: "Ta-Ha", arabicRoman: "Ta Ha", verses: 135 },
  { number: 21, englishName: "The Prophets", arabicRoman: "Al-Anbiya’", verses: 112 },
  { number: 22, englishName: "The Pilgrimage", arabicRoman: "Al-Hajj", verses: 78 },
  { number: 23, englishName: "The Believers", arabicRoman: "Al-Mu’minun", verses: 118 },
  { number: 24, englishName: "The Light", arabicRoman: "Al-Nur", verses: 64 },
  { number: 25, englishName: "The Criterion", arabicRoman: "Al-Furqan", verses: 77 },
  { number: 26, englishName: "The Poets", arabicRoman: "Al-Shu‘ara’", verses: 227 },
  { number: 27, englishName: "The Ant", arabicRoman: "Al-Naml", verses: 93 },
  { number: 28, englishName: "The Stories", arabicRoman: "Al-Qasas", verses: 88 },
  { number: 29, englishName: "The Spider", arabicRoman: "Al-‘Ankabut", verses: 69 },
  { number: 30, englishName: "The Romans", arabicRoman: "Al-Rum", verses: 60 },
  { number: 31, englishName: "Luqman", arabicRoman: "Luqman", verses: 34 },
  { number: 32, englishName: "The Prostration", arabicRoman: "Al-Sajdah", verses: 30 },
  { number: 33, englishName: "The Confederates", arabicRoman: "Al-Ahzab", verses: 73 },
  { number: 34, englishName: "Sheba", arabicRoman: "Saba’", verses: 54 },
  { number: 35, englishName: "The Originator", arabicRoman: "Fatir", verses: 45 },
  { number: 36, englishName: "Ya-Sin", arabicRoman: "Ya Sin", verses: 83 },
  { number: 37, englishName: "Those Who Set The Ranks", arabicRoman: "Al-Saffat", verses: 182 },
  { number: 38, englishName: "Sad", arabicRoman: "Sad", verses: 88 },
  { number: 39, englishName: "The Groups", arabicRoman: "Al-Zumar", verses: 75 },
  { number: 40, englishName: "The Forgiver", arabicRoman: "Ghafir", verses: 85 },
  { number: 41, englishName: "Explained in Detail", arabicRoman: "Fussilat", verses: 54 },
  { number: 42, englishName: "Consultation", arabicRoman: "Al-Shura", verses: 53 },
  { number: 43, englishName: "Ornaments of Gold", arabicRoman: "Al-Zukhruf", verses: 89 },
  { number: 44, englishName: "The Smoke", arabicRoman: "Al-Dukhan", verses: 59 },
  { number: 45, englishName: "The Crouching", arabicRoman: "Al-Jathiyah", verses: 37 },
  { number: 46, englishName: "The Wind-Curved Sandhills", arabicRoman: "Al-Ahqaf", verses: 35 },
  { number: 47, englishName: "Muhammad", arabicRoman: "Muhammad", verses: 38 },
  { number: 48, englishName: "The Victory", arabicRoman: "Al-Fath", verses: 29 },
  { number: 49, englishName: "The Rooms", arabicRoman: "Al-Hujurat", verses: 18 },
  { number: 50, englishName: "Qaf", arabicRoman: "Qaf", verses: 45 },
  { number: 51, englishName: "The Winnowing Winds", arabicRoman: "Al-Dhariyat", verses: 60 },
  { number: 52, englishName: "The Mount", arabicRoman: "Al-Tur", verses: 49 },
  { number: 53, englishName: "The Star", arabicRoman: "Al-Najm", verses: 62 },
  { number: 54, englishName: "The Moon", arabicRoman: "Al-Qamar", verses: 55 },
  { number: 55, englishName: "The Beneficent", arabicRoman: "Al-Rahman", verses: 78 },
  { number: 56, englishName: "The Inevitable", arabicRoman: "Al-Waqi‘ah", verses: 96 },
  { number: 57, englishName: "The Iron", arabicRoman: "Al-Hadid", verses: 29 },
  { number: 58, englishName: "The Pleading Woman", arabicRoman: "Al-Mujadalah", verses: 22 },
  { number: 59, englishName: "The Exile", arabicRoman: "Al-Hashr", verses: 24 },
  { number: 60, englishName: "She That is to be Examined", arabicRoman: "Al-Mumtahanah", verses: 13 },
  { number: 61, englishName: "The Ranks", arabicRoman: "Al-Saff", verses: 14 },
  { number: 62, englishName: "The Congregation", arabicRoman: "Al-Jumu‘ah", verses: 11 },
  { number: 63, englishName: "The Hypocrites", arabicRoman: "Al-Munafiqun", verses: 11 },
  { number: 64, englishName: "Mutual Disillusion", arabicRoman: "Al-Taghabun", verses: 18 },
  { number: 65, englishName: "Divorce", arabicRoman: "Al-Talaq", verses: 12 },
  { number: 66, englishName: "The Prohibition", arabicRoman: "Al-Tahrim", verses: 12 },
  { number: 67, englishName: "The Sovereignty", arabicRoman: "Al-Mulk", verses: 30 },
  { number: 68, englishName: "The Pen", arabicRoman: "Al-Qalam", verses: 52 },
  { number: 69, englishName: "The Reality", arabicRoman: "Al-Haqqah", verses: 52 },
  { number: 70, englishName: "The Ascending Stairways", arabicRoman: "Al-Ma‘arij", verses: 44 },
  { number: 71, englishName: "Noah", arabicRoman: "Nuh", verses: 28 },
  { number: 72, englishName: "The Jinn", arabicRoman: "Al-Jinn", verses: 28 },
  { number: 73, englishName: "The Enshrouded One", arabicRoman: "Al-Muzzammil", verses: 20 },
  { number: 74, englishName: "The Cloaked One", arabicRoman: "Al-Muddaththir", verses: 56 },
  { number: 75, englishName: "The Resurrection", arabicRoman: "Al-Qiyamah", verses: 40 },
  { number: 76, englishName: "Man", arabicRoman: "Al-Insan", verses: 31 },
  { number: 77, englishName: "The Emissaries", arabicRoman: "Al-Mursalat", verses: 50 },
  { number: 78, englishName: "The Tidings", arabicRoman: "Al-Naba’", verses: 40 },
  { number: 79, englishName: "Those Who Drag Forth", arabicRoman: "Al-Nazi‘at", verses: 46 },
  { number: 80, englishName: "He Frowned", arabicRoman: "‘Abasa", verses: 42 },
  { number: 81, englishName: "The Overthrowing", arabicRoman: "Al-Takwir", verses: 29 },
  { number: 82, englishName: "The Cleaving", arabicRoman: "Al-Infitar", verses: 19 },
  { number: 83, englishName: "Defrauding", arabicRoman: "Al-Mutaffifin", verses: 36 },
  { number: 84, englishName: "The Splitting Open", arabicRoman: "Al-Inshiqaq", verses: 25 },
  { number: 85, englishName: "The Mansions of the Stars", arabicRoman: "Al-Buruj", verses: 22 },
  { number: 86, englishName: "The Morning Star", arabicRoman: "Al-Tariq", verses: 17 },
  { number: 87, englishName: "The Most High", arabicRoman: "Al-A‘la", verses: 19 },
  { number: 88, englishName: "The Overwhelming", arabicRoman: "Al-Ghashiyah", verses: 26 },
  { number: 89, englishName: "The Dawn", arabicRoman: "Al-Fajr", verses: 30 },
  { number: 90, englishName: "The City", arabicRoman: "Al-Balad", verses: 20 },
  { number: 91, englishName: "The Sun", arabicRoman: "Al-Shams", verses: 15 },
  { number: 92, englishName: "The Night", arabicRoman: "Al-Layl", verses: 21 },
  { number: 93, englishName: "The Morning Hours", arabicRoman: "Al-Duha", verses: 11 },
  { number: 94, englishName: "The Relief", arabicRoman: "Al-Sharh", verses: 8 },
  { number: 95, englishName: "The Fig", arabicRoman: "Al-Tin", verses: 8 },
  { number: 96, englishName: "The Clot", arabicRoman: "Al-‘Alaq", verses: 19 },
  { number: 97, englishName: "The Power", arabicRoman: "Al-Qadr", verses: 5 },
  { number: 98, englishName: "The Clear Proof", arabicRoman: "Al-Bayyinah", verses: 8 },
  { number: 99, englishName: "The Earthquake", arabicRoman: "Al-Zalzalah", verses: 8 },
  { number: 100, englishName: "The Courser", arabicRoman: "Al-‘Adiyat", verses: 11 },
  { number: 101, englishName: "The Calamity", arabicRoman: "Al-Qari‘ah", verses: 11 },
  { number: 102, englishName: "The Rivalry in world increase", arabicRoman: "Al-Takathur", verses: 8 },
  { number: 103, englishName: "The Declining Day", arabicRoman: "Al-‘Asr", verses: 3 },
  { number: 104, englishName: "The Traducer", arabicRoman: "Al-Humazah", verses: 9 },
  { number: 105, englishName: "The Elephant", arabicRoman: "Al-Fil", verses: 5 },
  { number: 106, englishName: "Quraysh", arabicRoman: "Quraysh", verses: 4 },
  { number: 107, englishName: "Small Kindnesses", arabicRoman: "Al-Ma‘un", verses: 7 },
  { number: 108, englishName: "Abundance", arabicRoman: "Al-Kawthar", verses: 3 },
  { number: 109, englishName: "The Disbelievers", arabicRoman: "Al-Kafirun", verses: 6 },
  { number: 110, englishName: "Divine Support", arabicRoman: "Al-Nasr", verses: 3 },
  { number: 111, englishName: "The Palm Fiber", arabicRoman: "Al-Masad", verses: 5 },
  { number: 112, englishName: "The Sincerity", arabicRoman: "Al-Ikhlas", verses: 4 },
  { number: 113, englishName: "The Daybreak", arabicRoman: "Al-Falaq", verses: 5 },
  { number: 114, englishName: "Mankind", arabicRoman: "Al-Nas", verses: 6 },
];