export const surahs = [
  { number: 1, englishName: "The Opening", arabicRoman: "Al-Fātiḥah", verses: 7 },
  { number: 2, englishName: "The Cow", arabicRoman: "Al-Baqarah", verses: 286 },
  { number: 3, englishName: "The Family of Imran", arabicRoman: "Āl ʿImrān", verses: 200 },
  { number: 4, englishName: "The Women", arabicRoman: "An-Nisāʾ", verses: 176 },
  { number: 5, englishName: "The Table Spread", arabicRoman: "Al-Māʾidah", verses: 120 },
  { number: 6, englishName: "The Cattle", arabicRoman: "Al-Anʿām", verses: 165 },
  { number: 7, englishName: "The Heights", arabicRoman: "Al-Aʿrāf", verses: 206 },
  { number: 8, englishName: "The Spoils of War", arabicRoman: "Al-Anfāl", verses: 75 },
  { number: 9, englishName: "The Repentance", arabicRoman: "At-Tawbah", verses: 129 },
  { number: 10, englishName: "Jonah", arabicRoman: "Yūnus", verses: 109 },
  { number: 11, englishName: "Hud", arabicRoman: "Hūd", verses: 123 },
  { number: 12, englishName: "Joseph", arabicRoman: "Yūsuf", verses: 111 },
  { number: 13, englishName: "The Thunder", arabicRoman: "Ar-Raʿd", verses: 43 },
  { number: 14, englishName: "Abraham", arabicRoman: "Ibrāhīm", verses: 52 },
  { number: 15, englishName: "The Rocky Tract", arabicRoman: "Al-Ḥijr", verses: 99 },
  { number: 16, englishName: "The Bee", arabicRoman: "An-Naḥl", verses: 128 },
  { number: 17, englishName: "The Night Journey", arabicRoman: "Al-Isrāʾ", verses: 111 },
  { number: 18, englishName: "The Cave", arabicRoman: "Al-Kahf", verses: 110 },
  { number: 19, englishName: "Mary", arabicRoman: "Maryam", verses: 98 },
  { number: 20, englishName: "Ta-Ha", arabicRoman: "Ṭā Hā", verses: 135 },
  { number: 21, englishName: "The Prophets", arabicRoman: "Al-Anbiyāʾ", verses: 112 },
  { number: 22, englishName: "The Pilgrimage", arabicRoman: "Al-Ḥajj", verses: 78 },
  { number: 23, englishName: "The Believers", arabicRoman: "Al-Muʾminūn", verses: 118 },
  { number: 24, englishName: "The Light", arabicRoman: "An-Nūr", verses: 64 },
  { number: 25, englishName: "The Criterion", arabicRoman: "Al-Furqān", verses: 77 },
  { number: 26, englishName: "The Poets", arabicRoman: "Ash-Shuʿarāʾ", verses: 227 },
  { number: 27, englishName: "The Ant", arabicRoman: "An-Naml", verses: 93 },
  { number: 28, englishName: "The Stories", arabicRoman: "Al-Qaṣaṣ", verses: 88 },
  { number: 29, englishName: "The Spider", arabicRoman: "Al-ʿAnkabūt", verses: 69 },
  { number: 30, englishName: "The Romans", arabicRoman: "Ar-Rūm", verses: 60 },
  { number: 31, englishName: "Luqman", arabicRoman: "Luqmān", verses: 34 },
  { number: 32, englishName: "The Prostration", arabicRoman: "As-Sajdah", verses: 30 },
  { number: 33, englishName: "The Confederates", arabicRoman: "Al-Aḥzāb", verses: 73 },
  { number: 34, englishName: "Sheba", arabicRoman: "Sabaʾ", verses: 54 },
  { number: 35, englishName: "The Originator", arabicRoman: "Fāṭir", verses: 45 },
  { number: 36, englishName: "Ya-Sin", arabicRoman: "Yā Sīn", verses: 83 },
  { number: 37, englishName: "Those Who Set The Ranks", arabicRoman: "Aṣ-Ṣāffāt", verses: 182 },
  { number: 38, englishName: "Sad", arabicRoman: "Ṣād", verses: 88 },
  { number: 39, englishName: "The Groups", arabicRoman: "Az-Zumar", verses: 75 },
  { number: 40, englishName: "The Forgiver", arabicRoman: "Ghāfir", verses: 85 },
  { number: 41, englishName: "Explained in Detail", arabicRoman: "Fuṣṣilat", verses: 54 },
  { number: 42, englishName: "Consultation", arabicRoman: "Ash-Shūrā", verses: 53 },
  { number: 43, englishName: "Ornaments of Gold", arabicRoman: "Az-Zukhruf", verses: 89 },
  { number: 44, englishName: "The Smoke", arabicRoman: "Ad-Dukhān", verses: 59 },
  { number: 45, englishName: "The Crouching", arabicRoman: "Al-Jāthiyah", verses: 37 },
  { number: 46, englishName: "The Wind-Curved Sandhills", arabicRoman: "Al-Aḥqāf", verses: 35 },
  { number: 47, englishName: "Muhammad", arabicRoman: "Muḥammad", verses: 38 },
  { number: 48, englishName: "The Victory", arabicRoman: "Al-Fatḥ", verses: 29 },
  { number: 49, englishName: "The Rooms", arabicRoman: "Al-Ḥujurāt", verses: 18 },
  { number: 50, englishName: "Qaf", arabicRoman: "Qāf", verses: 45 },
  { number: 51, englishName: "The Winnowing Winds", arabicRoman: "Adh-Dhāriyāt", verses: 60 },
  { number: 52, englishName: "The Mount", arabicRoman: "Aṭ-Ṭūr", verses: 49 },
  { number: 53, englishName: "The Star", arabicRoman: "An-Najm", verses: 62 },
  { number: 54, englishName: "The Moon", arabicRoman: "Al-Qamar", verses: 55 },
  { number: 55, englishName: "The Beneficent", arabicRoman: "Ar-Raḥmān", verses: 78 },
  { number: 56, englishName: "The Inevitable", arabicRoman: "Al-Wāqiʿah", verses: 96 },
  { number: 57, englishName: "The Iron", arabicRoman: "Al-Ḥadīd", verses: 29 },
  { number: 58, englishName: "The Pleading Woman", arabicRoman: "Al-Mujādilah", verses: 22 },
  { number: 59, englishName: "The Exile", arabicRoman: "Al-Ḥashr", verses: 24 },
  { number: 60, englishName: "She That is to be Examined", arabicRoman: "Al-Mumtaḥanah", verses: 13 },
  { number: 61, englishName: "The Ranks", arabicRoman: "Aṣ-Ṣaff", verses: 14 },
  { number: 62, englishName: "The Congregation", arabicRoman: "Al-Jumuʿah", verses: 11 },
  { number: 63, englishName: "The Hypocrites", arabicRoman: "Al-Munāfiqūn", verses: 11 },
  { number: 64, englishName: "Mutual Disillusion", arabicRoman: "At-Taghābun", verses: 18 },
  { number: 65, englishName: "Divorce", arabicRoman: "Aṭ-Ṭalāq", verses: 12 },
  { number: 66, englishName: "The Prohibition", arabicRoman: "At-Taḥrīm", verses: 12 },
  { number: 67, englishName: "The Sovereignty", arabicRoman: "Al-Mulk", verses: 30 },
  { number: 68, englishName: "The Pen", arabicRoman: "Al-Qalam", verses: 52 },
  { number: 69, englishName: "The Reality", arabicRoman: "Al-Ḥāqqah", verses: 52 },
  { number: 70, englishName: "The Ascending Stairways", arabicRoman: "Al-Maʿārij", verses: 44 },
  { number: 71, englishName: "Noah", arabicRoman: "Nūḥ", verses: 28 },
  { number: 72, englishName: "The Jinn", arabicRoman: "Al-Jinn", verses: 28 },
  { number: 73, englishName: "The Enshrouded One", arabicRoman: "Al-Muzzammil", verses: 20 },
  { number: 74, englishName: "The Cloaked One", arabicRoman: "Al-Muddaththir", verses: 56 },
  { number: 75, englishName: "The Resurrection", arabicRoman: "Al-Qiyāmah", verses: 40 },
  { number: 76, englishName: "Man", arabicRoman: "Al-Insān", verses: 31 },
  { number: 77, englishName: "The Emissaries", arabicRoman: "Al-Mursalāt", verses: 50 },
  { number: 78, englishName: "The Tidings", arabicRoman: "An-Nabaʾ", verses: 40 },
  { number: 79, englishName: "Those Who Drag Forth", arabicRoman: "An-Nāziʿāt", verses: 46 },
  { number: 80, englishName: "He Frowned", arabicRoman: "ʿAbasa", verses: 42 },
  { number: 81, englishName: "The Overthrowing", arabicRoman: "At-Takwīr", verses: 29 },
  { number: 82, englishName: "The Cleaving", arabicRoman: "Al-Infiṭār", verses: 19 },
  { number: 83, englishName: "Defrauding", arabicRoman: "Al-Muṭaffifīn", verses: 36 },
  { number: 84, englishName: "The Splitting Open", arabicRoman: "Al-Inshiqāq", verses: 25 },
  { number: 85, englishName: "The Mansions of the Stars", arabicRoman: "Al-Burūj", verses: 22 },
  { number: 86, englishName: "The Morning Star", arabicRoman: "Aṭ-Ṭāriq", verses: 17 },
  { number: 87, englishName: "The Most High", arabicRoman: "Al-Aʿlā", verses: 19 },
  { number: 88, englishName: "The Overwhelming", arabicRoman: "Al-Ghāshiyah", verses: 26 },
  { number: 89, englishName: "The Dawn", arabicRoman: "Al-Fajr", verses: 30 },
  { number: 90, englishName: "The City", arabicRoman: "Al-Balad", verses: 20 },
  { number: 91, englishName: "The Sun", arabicRoman: "Ash-Shams", verses: 15 },
  { number: 92, englishName: "The Night", arabicRoman: "Al-Layl", verses: 21 },
  { number: 93, englishName: "The Morning Hours", arabicRoman: "Aḍ-Ḍuḥā", verses: 11 },
  { number: 94, englishName: "The Relief", arabicRoman: "Ash-Sharḥ", verses: 8 },
  { number: 95, englishName: "The Fig", arabicRoman: "At-Tīn", verses: 8 },
  { number: 96, englishName: "The Clot", arabicRoman: "Al-ʿAlaq", verses: 19 },
  { number: 97, englishName: "The Power", arabicRoman: "Al-Qadr", verses: 5 },
  { number: 98, englishName: "The Clear Proof", arabicRoman: "Al-Bayyinah", verses: 8 },
  { number: 99, englishName: "The Earthquake", arabicRoman: "Az-Zalzalah", verses: 8 },
  { number: 100, englishName: "The Courser", arabicRoman: "Al-ʿĀdiyāt", verses: 11 },
  { number: 101, englishName: "The Calamity", arabicRoman: "Al-Qāriʿah", verses: 11 },
  { number: 102, englishName: "The Rivalry in world increase", arabicRoman: "At-Takāthur", verses: 8 },
  { number: 103, englishName: "The Declining Day", arabicRoman: "Al-ʿAṣr", verses: 3 },
  { number: 104, englishName: "The Traducer", arabicRoman: "Al-Humazah", verses: 9 },
  { number: 105, englishName: "The Elephant", arabicRoman: "Al-Fīl", verses: 5 },
  { number: 106, englishName: "Quraysh", arabicRoman: "Quraysh", verses: 4 },
  { number: 107, englishName: "Small Kindnesses", arabicRoman: "Al-Māʿūn", verses: 7 },
  { number: 108, englishName: "Abundance", arabicRoman: "Al-Kawthar", verses: 3 },
  { number: 109, englishName: "The Disbelievers", arabicRoman: "Al-Kāfirūn", verses: 6 },
  { number: 110, englishName: "Divine Support", arabicRoman: "An-Naṣr", verses: 3 },
  { number: 111, englishName: "The Palm Fiber", arabicRoman: "Al-Masad", verses: 5 },
  { number: 112, englishName: "The Sincerity", arabicRoman: "Al-Ikhlāṣ", verses: 4 },
  { number: 113, englishName: "The Daybreak", arabicRoman: "Al-Falaq", verses: 5 },
  { number: 114, englishName: "Mankind", arabicRoman: "An-Nās", verses: 6 },
];
